security:
    encoders:
        App\Entity\Participant:
            algorithm: bcrypt

    providers:
        main_provider:
            entity:
                class: App\Entity\Participant
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: main_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            anonymous: lazy
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            logout_on_user_change: true
            logout:
                path: app_logout
                target: /



    access_control:


        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
            # - { path: ^/profile, roles: ROLE_USER }
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]