security:
    encoders:
        App\Entity\Participant:
            algorithm: bcrypt

    providers:
        main_provider:
            entity:
                class: App\Entity\Participant
                property: pseudo
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: main_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            anonymous: lazy
            form_login:
                login_path: login
                check_path: login
            logout_on_user_change: true
            logout:
                path: app_logout
                target: /



    access_control:
#        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, roles: ROLE_USER }
        #- { path: ^/, roles: ROLE_USER } toutes les pages sont protégés et seuls les connectés peuvent aller sur les pages du site =>
        #{ path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY } ET { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }DOIT ETRE EN DERNIER SINON LES AUTRES SONT VALIDE AVANT ET LAISSE PASSER;

    role_hierarchy:

        ROLE_ADMIN: [ROLE_USER]