vich_uploader:
    db_driver: orm

    mappings:
        participant_images:
            uri_prefix: '%app.path.participant_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.participant_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


